def dimacs(G, c, k, filename):
    with open(filename, "w") as f:
        # write the header
        f.write("c This is a graph generated by the stochastic block model in DIMACS format.\n")

        f.write("p EDGE {} {}\n".format(G.number_of_nodes(), G.number_of_edges(), k))
        # now write all edges
        for u, v in G.edges():
            f.write("e {} {}\n".format(u, v))
        for i in range(len(c)):
            f.write("n {} {}\n".format(c[i], i+1))

